In [1]:
import pandas as pd

In [7]:
df_match = pd.read_csv(r"C:\Users\sumit\OneDrive\Desktop\WorldCup2022\raw_data\match_result.csv")

**match_result**

In [57]:
df_match
df_match = df_match.replace("U.A.E.","United Arab Emirates")

In [58]:
match_id = {}

for index,row in df_match.iterrows():
    key1 = row["Team 1"] + ' VS ' + row["Team 2"]
    key2 = row["Team 2"] + ' VS ' + row["Team 1"]
    
    match_id[key1]  = row["id"]
    match_id[key2]  = row["id"]
    
match_id

{'Namibia VS Sri Lanka': 'T20I # 1823',
 'Sri Lanka VS Namibia': 'T20I # 1823',
 'Netherlands VS United Arab Emirates': 'T20I # 1825',
 'United Arab Emirates VS Netherlands': 'T20I # 1825',
 'Scotland VS West Indies': 'T20I # 1826',
 'West Indies VS Scotland': 'T20I # 1826',
 'Ireland VS Zimbabwe': 'T20I # 1828',
 'Zimbabwe VS Ireland': 'T20I # 1828',
 'Namibia VS Netherlands': 'T20I # 1830',
 'Netherlands VS Namibia': 'T20I # 1830',
 'Sri Lanka VS United Arab Emirates': 'T20I # 1832',
 'United Arab Emirates VS Sri Lanka': 'T20I # 1832',
 'Ireland VS Scotland': 'T20I # 1833',
 'Scotland VS Ireland': 'T20I # 1833',
 'West Indies VS Zimbabwe': 'T20I # 1834',
 'Zimbabwe VS West Indies': 'T20I # 1834',
 'Netherlands VS Sri Lanka': 'T20I # 1835',
 'Sri Lanka VS Netherlands': 'T20I # 1835',
 'Namibia VS United Arab Emirates': 'T20I # 1836',
 'United Arab Emirates VS Namibia': 'T20I # 1836',
 'Ireland VS West Indies': 'T20I # 1837',
 'West Indies VS Ireland': 'T20I # 1837',
 'Scotland VS Zimbabwe': 'T20I # 1838',
 'Zimbabwe VS Scotland': 'T20I # 1838',
 'Australia VS New Zealand': 'T20I # 1839',
 'New Zealand VS Australia': 'T20I # 1839',
 'Afghanistan VS England': 'T20I # 1840',
 'England VS Afghanistan': 'T20I # 1840',
 'Ireland VS Sri Lanka': 'T20I # 1841',
 'Sri Lanka VS Ireland': 'T20I # 1841',
 'India VS Pakistan': 'T20I # 1842',
 'Pakistan VS India': 'T20I # 1842',
 'Bangladesh VS Netherlands': 'T20I # 1843',
 'Netherlands VS Bangladesh': 'T20I # 1843',
 'South Africa VS Zimbabwe': 'T20I # 1844',
 'Zimbabwe VS South Africa': 'T20I # 1844',
 'Australia VS Sri Lanka': 'T20I # 1845',
 'Sri Lanka VS Australia': 'T20I # 1845',
 'England VS Ireland': 'T20I # 1846',
 'Ireland VS England': 'T20I # 1846',
 'Afghanistan VS New Zealand': 'T20I # 1846a',
 'New Zealand VS Afghanistan': 'T20I # 1846a',
 'Bangladesh VS South Africa': 'T20I # 1847',
 'South Africa VS Bangladesh': 'T20I # 1847',
 'India VS Netherlands': 'T20I # 1848',
 'Netherlands VS India': 'T20I # 1848',
 'Pakistan VS Zimbabwe': 'T20I # 1849',
 'Zimbabwe VS Pakistan': 'T20I # 1849',
 'Afghanistan VS Ireland': 'T20I # 1849a',
 'Ireland VS Afghanistan': 'T20I # 1849a',
 'Australia VS England': 'T20I # 1849b',
 'England VS Australia': 'T20I # 1849b',
 'New Zealand VS Sri Lanka': 'T20I # 1850',
 'Sri Lanka VS New Zealand': 'T20I # 1850',
 'Bangladesh VS Zimbabwe': 'T20I # 1851',
 'Zimbabwe VS Bangladesh': 'T20I # 1851',
 'Netherlands VS Pakistan': 'T20I # 1852',
 'Pakistan VS Netherlands': 'T20I # 1852',
 'India VS South Africa': 'T20I # 1853',
 'South Africa VS India': 'T20I # 1853',
 'Australia VS Ireland': 'T20I # 1855',
 'Ireland VS Australia': 'T20I # 1855',
 'Afghanistan VS Sri Lanka': 'T20I # 1856',
 'Sri Lanka VS Afghanistan': 'T20I # 1856',
 'England VS New Zealand': 'T20I # 1858',
 'New Zealand VS England': 'T20I # 1858',
 'Netherlands VS Zimbabwe': 'T20I # 1859',
 'Zimbabwe VS Netherlands': 'T20I # 1859',
 'Bangladesh VS India': 'T20I # 1860',
 'India VS Bangladesh': 'T20I # 1860',
 'Pakistan VS South Africa': 'T20I # 1861',
 'South Africa VS Pakistan': 'T20I # 1861',
 'Ireland VS New Zealand': 'T20I # 1862',
 'New Zealand VS Ireland': 'T20I # 1862',
 'Australia VS Afghanistan': 'T20I # 1864',
 'Afghanistan VS Australia': 'T20I # 1864',
 'England VS Sri Lanka': 'T20I # 1867',
 'Sri Lanka VS England': 'T20I # 1867',
 'Netherlands VS South Africa': 'T20I # 1871',
 'South Africa VS Netherlands': 'T20I # 1871',
 'Bangladesh VS Pakistan': 'T20I # 1872',
 'Pakistan VS Bangladesh': 'T20I # 1872',
 'India VS Zimbabwe': 'T20I # 1873',
 'Zimbabwe VS India': 'T20I # 1873',
 'New Zealand VS Pakistan': 'T20I # 1877',
 'Pakistan VS New Zealand': 'T20I # 1877',
 'England VS India': 'T20I # 1878',
 'India VS England': 'T20I # 1878',
 'England VS Pakistan': 'T20I # 1879',
 'Pakistan VS England': 'T20I # 1879'}

**batting summery**

In [24]:
batting_summery = pd.read_csv(r"C:\Users\sumit\OneDrive\Desktop\WorldCup2022\raw_data\battingSummery.csv")
batting_summery[5:20]

,team,teamInnings,inning,position,batsman,dismissal,runs,balls,M,4s,6s,SR
5,Namibia VS Sri Lanka,Namibia,Inning1,6,Jan Frylinck,run out (Gunathilaka/Mendis),44,28,44,4,0,157.14
6,Namibia VS Sri Lanka,Namibia,Inning1,7,David Wiese,c Mendis b Theekshana,0,1,4,0,0,0.00
7,Namibia VS Sri Lanka,Namibia,Inning1,8,JJ Smit,not out,31,16,29,2,2,193.75
8,Namibia VS Sri Lanka,Sri Lanka,Inning2,1,Pathum Nissanka,c Smit b Shikongo,9,10,16,1,0,90.00
9,Namibia VS Sri Lanka,Sri Lanka,Inning2,2,Kusal Mendisâ€,c Green b Wiese,6,6,8,0,0,100.00
10,Namibia VS Sri Lanka,Sri Lanka,Inning2,3,Dhananjaya de Silva,c Shikongo b Frylinck,12,11,25,1,0,109.09
11,Namibia VS Sri Lanka,Sri Lanka,Inning2,4,Danushka Gunathilaka,c Green b Shikongo,0,1,2,0,0,0.00
12,Namibia VS Sri Lanka,Sri Lanka,Inning2,5,Bhanuka Rajapaksa,c la Cock b Scholtz,20,21,39,2,0,95.23
13,Namibia VS Sri Lanka,Sri Lanka,Inning2,6,Dasun Shanaka(c),c Green b Frylinck,29,23,37,2,1,126.08
14,Namibia VS Sri Lanka,Sri Lanka,Inning2,7,Wanindu Hasaranga de Silva,c Loftie-Eaton b Scholtz,4,8,9,0,0,50.00
15,Namibia VS Sri Lanka,Sri Lanka,Inning2,8,Chamika Karunaratne,c Baard b Smit,5,8,15,0,0,62.50
16,Namibia VS Sri Lanka,Sri Lanka,Inning2,9,Pramod Madushan,run out (van Lingen/Green),0,0,4,0,0,0.00
17,Namibia VS Sri Lanka,Sri Lanka,Inning2,10,Dushmantha Chameera,c Erasmus b Wiese,8,15,20,0,0,53.33
18,Namibia VS Sri Lanka,Sri Lanka,Inning2,11,Maheesh Theekshana,not out,11,11,14,0,1,100.00
19,United Arab Emirates VS Netherlands,United Arab Emirates,Inning1,1,Chirag Suri,c Edwards b van der Merwe,12,20,28,1,0,60.00

In [25]:
# creating out and not out column

batting_summery["out/not_out"] = batting_summery["dismissal"].apply(lambda x : "not out" if x=="not out" else "out" )

In [30]:
# removing the unnecessary words from the data

batting_summery["batsman"] = batting_summery["batsman"].apply(lambda x: x.replace("â€ ",""))
# batting_summery["batsman"] = batting_summery["batsman"].apply(lambda x: x.replace("(c)"),"")
# batting_summery["batsman"] = batting_summery["batsman"].apply(lambda x: x.replace("(wk)"),"")

In [59]:
# data Modelling for batting

batting_summery["id"] = batting_summery["team"].map(match_id)

batting_summery

,team,teamInnings,inning,position,batsman,dismissal,runs,balls,M,4s,6s,SR,out/not_out,id
0,Namibia VS Sri Lanka,Namibia,Inning1,1,Michael van Lingen,c Pramod Madushan b Chameera,3,6,7,0,0,50.00,out,T20I # 1823
1,Namibia VS Sri Lanka,Namibia,Inning1,2,Divan la Cock,c Shanaka b Pramod Madushan,9,9,15,1,0,100.00,out,T20I # 1823
2,Namibia VS Sri Lanka,Namibia,Inning1,3,Jan Nicol Loftie-Eaton,c Mendis b Karunaratne,20,12,18,1,2,166.66,out,T20I # 1823
3,Namibia VS Sri Lanka,Namibia,Inning1,4,Stephan Baard,c DM de Silva b Pramod Madushan,26,24,49,2,0,108.33,out,T20I # 1823
4,Namibia VS Sri Lanka,Namibia,Inning1,5,Gerhard Erasmus(c),c Gunathilaka b PWH de Silva,20,24,30,0,0,83.33,out,T20I # 1823
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
694,Pakistan VS England,England,Inning2,3,Phil Salt,c Iftikhar Ahmed b Haris Rauf,10,9,16,2,0,111.11,out,T20I # 1879
695,Pakistan VS England,England,Inning2,4,Ben Stokes,not out,52,49,81,5,1,106.12,not out,T20I # 1879
696,Pakistan VS England,England,Inning2,5,Harry Brook,c Shaheen Shah Afridi b Shadab Khan,20,23,36,1,0,86.95,out,T20I # 1879
697,Pakistan VS England,England,Inning2,6,Moeen Ali,b Mohammad Wasim,19,13,30,3,0,146.15,out,T20I # 1879
698,Pakistan VS England,England,Inning2,7,Liam Livingstone,not out,1,1,3,0,0,100.00,not out,T20I # 1879

In [60]:
batting_summery.to_csv(r"C:\Users\sumit\OneDrive\Desktop\WorldCup2022\cleaned_data\batting_summery.csv",index=False)

**Bowling Summery**

In [43]:
# data Modelling for batting

bowling_summery = pd.read_csv(r"C:\Users\sumit\OneDrive\Desktop\WorldCup2022\raw_data\bowlingSummary.csv")

bowling_summery

,match,bowlingTeam,bowler,over,maiden,runs,wicket,economy,0s,4s,6s,wide,NB
0,Namibia VS Sri Lanka,Sri Lanka,Maheesh Theekshana,4.0,0,23,1,5.75,7,0,0,2,0
1,Namibia VS Sri Lanka,Sri Lanka,Dushmantha Chameera,4.0,0,39,1,9.75,6,3,1,2,0
2,Namibia VS Sri Lanka,Sri Lanka,Pramod Madushan,4.0,0,37,2,9.25,6,3,1,0,0
3,Namibia VS Sri Lanka,Sri Lanka,Chamika Karunaratne,4.0,0,36,1,9.00,7,3,1,1,0
4,Namibia VS Sri Lanka,Sri Lanka,Wanindu Hasaranga de Silva,4.0,0,27,1,6.75,8,1,1,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
495,Pakistan VS England,Pakistan,Naseem Shah,4.0,0,30,0,7.50,15,3,1,1,0
496,Pakistan VS England,Pakistan,Haris Rauf,4.0,0,23,2,5.75,13,3,0,1,0
497,Pakistan VS England,Pakistan,Shadab Khan,4.0,0,20,1,5.00,10,1,0,0,0
498,Pakistan VS England,Pakistan,Mohammad Wasim,4.0,0,38,1,9.50,5,5,0,2,0
499,Pakistan VS England,Pakistan,Iftikhar Ahmed,0.5,0,13,0,15.60,0,1,1,0,0

In [61]:
bowling_summery["id"] = bowling_summery["match"].map(match_id)

In [62]:
bowling_summery[10:30]

,match,bowlingTeam,bowler,over,maiden,runs,wicket,economy,0s,4s,6s,wide,NB,id
10,Namibia VS Sri Lanka,Namibia,Jan Frylinck,4.0,0,26,2,6.50,10,0,2,1,0,T20I # 1823
11,United Arab Emirates VS Netherlands,Netherlands,Fred Klaassen,4.0,0,13,2,3.25,18,0,0,3,0,T20I # 1825
12,United Arab Emirates VS Netherlands,Netherlands,Tim Pringle,4.0,0,13,1,3.25,11,0,0,0,0,T20I # 1825
13,United Arab Emirates VS Netherlands,Netherlands,Logan van Beek,2.0,0,19,0,9.50,5,0,2,1,0,T20I # 1825
14,United Arab Emirates VS Netherlands,Netherlands,Bas de Leede,3.0,0,19,3,6.33,9,2,0,2,0,T20I # 1825
15,United Arab Emirates VS Netherlands,Netherlands,Paul van Meekeren,4.0,0,21,0,5.25,11,1,0,0,0,T20I # 1825
16,United Arab Emirates VS Netherlands,Netherlands,Roelof van der Merwe,3.0,0,19,1,6.33,7,0,1,0,0,T20I # 1825
17,United Arab Emirates VS Netherlands,United Arab Emirates,Junaid Siddique,4.0,0,24,3,6.00,10,2,0,1,0,T20I # 1825
18,United Arab Emirates VS Netherlands,United Arab Emirates,Basil Hameed,1.0,0,7,1,7.00,4,0,1,0,0,T20I # 1825
19,United Arab Emirates VS Netherlands,United Arab Emirates,Aayan Afzal Khan,3.0,0,15,1,5.00,8,1,0,0,0,T20I # 1825
20,United Arab Emirates VS Netherlands,United Arab Emirates,Karthik Meiyappan,4.0,0,22,1,5.50,11,2,0,0,0,T20I # 1825
21,United Arab Emirates VS Netherlands,United Arab Emirates,Zahoor Khan,4.0,0,11,1,2.75,14,0,0,0,0,T20I # 1825
22,United Arab Emirates VS Netherlands,United Arab Emirates,Zawar Farid,2.5,0,24,0,8.47,2,2,0,0,0,T20I # 1825
23,United Arab Emirates VS Netherlands,United Arab Emirates,Kashif Daud,1.0,0,5,0,5.00,1,0,0,0,0,T20I # 1825
24,Scotland VS West Indies,West Indies,Kyle Mayers,2.0,0,24,0,12.00,5,5,0,2,0,T20I # 1826
25,Scotland VS West Indies,West Indies,Akeal Hosein,4.0,0,31,0,7.75,8,2,1,0,0,T20I # 1826
26,Scotland VS West Indies,West Indies,Alzarri Joseph,4.0,0,28,2,7.00,9,3,0,2,0,T20I # 1826
27,Scotland VS West Indies,West Indies,Obed McCoy,3.0,0,25,0,8.33,6,4,0,0,0,T20I # 1826
28,Scotland VS West Indies,West Indies,Jason Holder,3.0,0,14,2,4.66,8,1,0,0,0,T20I # 1826
29,Scotland VS West Indies,West Indies,Odean Smith,4.0,0,31,1,7.75,6,3,0,1,0,T20I # 1826

In [63]:
bowling_summery.to_csv(r"C:\Users\sumit\OneDrive\Desktop\WorldCup2022\cleaned_data\bowling_summery.csv",index=False)

**player summery**